
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderItem   
  template:
    metadata:
      labels:
        app: OrderItem
    spec:
      containers:
      - name: orderitem
        image: first1cr.azurecr.io/orderitemrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: secondapisn

---
apiVersion: v1
kind: Service
metadata:
  name: orderitem
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: OrderItem